import { StyleComparison } from "../models/style-comparison.model";

export const beerDataComparison: StyleComparison[] = [
    { id: 1, style1: "American Amber Ale", style2: "American Brown Ale", style3: "American Pale Ale" },
    { id: 2, style1: "American Amber Ale", style2: "American Pale Ale", style3: "California Common" },
    { id: 3, style1: "American Barleywine", style2: "Double IPA", style3: "English Barleywine" },
    { id: 4, style1: "American Barleywine", style2: "English Barleywine", style3: "Wee Heavy" },
    { id: 5, style1: "American Barleywine", style2: "Old Ale", style3: "Wee Heavy" },
    { id: 6, style1: "American Brown Ale", style2: "American Pale Ale", style3: "California Common" },
    { id: 7, style1: "American Brown Ale", style2: "British Brown Ale", style3: "Dark Mild" },
    { id: 9, style1: "American IPA", style2: "Double IPA", style3: "English IPA" },
    { id: 10, style1: "American Pale Ale", style2: "Belgian Pale Ale", style3: "Strong Bitter" },
    { id: 11, style1: "American Pale Ale", style2: "English Barleywine", style3: "Wee Heavy" },
    { id: 12, style1: "American Stout", style2: "Foreign Extra Stout", style3: "Irish Stout" },
    { id: 13, style1: "American Stout", style2: "Irish Stout", style3: "Oatmeal Stout" },
    { id: 14, style1: "American Stout", style2: "American Porter", style3: "Irish Stout" },
    { id: 15, style1: "American Stout", style2: "Irish Stout", style3: "Sweet Stout" },
    { id: 16, style1: "American Stout", style2: "Foreign Extra Stout", style3: "Oatmeal Stout" },
    { id: 17, style1: "American Porter", style2: "American Stout", style3: "Foreign Extra Stout" },
    { id: 18, style1: "American Stout", style2: "Foreign Extra Stout", style3: "Sweet Stout" },
    { id: 21, style1: "American Wheat Beer", style2: "Lambic", style3: "Witbier" },
    { id: 22, style1: "American Wheat Beer", style2: "Weissbier", style3: "Witbier" },
    { id: 23, style1: "Baltic Porter", style2: "Belgian Dark Strong Ale", style3: "Imperial Stout" },
    { id: 24, style1: "Belgian Blond Ale", style2: "Belgian Dubbel", style3: "Belgian Tripel" },
    { id: 25, style1: "Belgian Blond Ale", style2: "Belgian Golden Strong Ale", style3: "Belgian Tripel" },
    { id: 26, style1: "Belgian Blond Ale", style2: "Belgian Pale Ale", style3: "Saison" },
    { id: 27, style1: "Belgian Dark Strong Ale", style2: "Double IPA", style3: "Wee Heavy" },
    { id: 28, style1: "Belgian Dark Strong Ale", style2: "Belgian Dubbel", style3: "Weizenbock" },
    { id: 29, style1: "Belgian Pale Ale", style2: "Bière de Garde", style3: "Saison" },
    { id: 30, style1: "Berliner Weisse", style2: "Flanders Red Ale", style3: "Lambic" },
    { id: 31, style1: "Berliner Weisse", style2: "Gueuze", style3: "Lambic" },
    { id: 32, style1: "Berliner Weisse", style2: "Weissbier", style3: "Witbier" },
    { id: 34, style1: "Bière de Garde", style2: "California Common", style3: "International Amber Lager" },
    { id: 35, style1: "Blonde Ale", style2: "Cream Ale", style3: "Kölsch" },
    { id: 37, style1: "Czech Premium Pale Lager", style2: "German Pils", style3: "International Pale Lager" },
    { id: 38, style1: "American Lager", style2: "Czech Premium Pale Lager", style3: "German Pils" },
    { id: 39, style1: "American Porter", style2: "English Porter", style3: "Irish Stout" },
    { id: 41, style1: "British Brown Ale", style2: "English Porter", style3: "Munich Dunkel" },
    { id: 42, style1: "English Porter", style2: "Munich Dunkel", style3: "Schwarzbier" },
    { id: 44, style1: "California Common", style2: "Irish Red Ale", style3: "Märzen" },
    { id: 46, style1: "Cream Ale", style2: "Kölsch", style3: "Munich Helles" },
    { id: 47, style1: "International Dark Lager", style2: "Munich Dunkel", style3: "Schwarzbier" },
    { id: 48, style1: "Doppelbock", style2: "Eisbock", style3: "Helles Bock" },
    { id: 49, style1: "Doppelbock", style2: "Dunkles Bock", style3: "Eisbock" },
    { id: 50, style1: "Doppelbock", style2: "Dunkles Bock", style3: "Helles Bock" },
    { id: 51, style1: "Doppelbock", style2: "Dunkles Bock", style3: "Weizenbock" },
    { id: 52, style1: "German Pils", style2: "German Helles Exportbier", style3: "Munich Helles" },
    { id: 53, style1: "Foreign Extra Stout", style2: "Irish Stout", style3: "Sweet Stout" },
    { id: 54, style1: "American Porter", style2: "Irish Stout", style3: "Schwarzbier" },
    { id: 56, style1: "Dunkles Weissbier", style2: "Weissbier", style3: "Weizenbock" },
    { id: 57, style1: "Altbier", style2: "International Amber Lager", style3: "Irish Red Ale" },
    { id: 58, style1: "Altbier", style2: "International Amber Lager", style3: "Märzen" },
    { id: 59, style1: "Altbier", style2: "Best Bitter", style3: "Märzen" },
    { id: 60, style1: "Altbier", style2: "Märzen", style3: "Vienna Lager" },
    { id: 61, style1: "Dunkles Bock", style2: "Eisbock", style3: "Helles Bock" },
    { id: 62, style1: "English Barleywine", style2: "Imperial Stout", style3: "Wee Heavy" },
    { id: 63, style1: "English Barleywine", style2: "Old Ale", style3: "Wee Heavy" },
    { id: 64, style1: "Flanders Red Ale", style2: "Lambic", style3: "Oud Bruin" },
    { id: 65, style1: "American Porter", style2: "Baltic Porter", style3: "Foreign Extra Stout" },
    { id: 66, style1: "American Porter", style2: "Foreign Extra Stout", style3: "Sweet Stout" },
    { id: 67, style1: "Fruit Lambic", style2: "Gueuze", style3: "Lambic" },
    { id: 68, style1: "German Pils", style2: "Munich Helles", style3: "Schwarzbier" },
    { id: 69, style1: "International Amber Lager", style2: "Irish Red Ale", style3: "Märzen" },
    { id: 70, style1: "American Lager", style2: "American Light Lager", style3: "International Pale Lager" },
    { id: 71, style1: "Dark Mild", style2: "Ordinary Bitter", style3: "Scottish Light" },
    { id: 73, style1: "Munich Helles", style2: "Munich Dunkel", style3: "Märzen" },
    { id: 74, style1: "Munich Helles", style2: "Märzen", style3: "Vienna Lager" },
    { id: 75, style1: "Best Bitter", style2: "International Amber Lager", style3: "Märzen" },
    { id: 76, style1: "Dunkles Bock", style2: "Märzen", style3: "Rauchbier" },
    { id: 77, style1: "Scottish Export", style2: "Scottish Heavy", style3: "Wee Heavy" },
    { id: 78, style1: "Dark Mild", style2: "Scottish Heavy", style3: "Scottish Light" },
    { id: 79, style1: "Scottish Export", style2: "Scottish Heavy", style3: "Scottish Light" },
    { id: 80, style1: "Ordinary Bitter", style2: "Scottish Heavy", style3: "Scottish Light" },
    { id: 81, style1: "Scottish Heavy", style2: "Scottish Light", style3: "Wee Heavy" },
    { id: 82, style1: "Scottish Export", style2: "Scottish Light", style3: "Wee Heavy" },
    { id: 84, style1: "Best Bitter", style2: "Ordinary Bitter", style3: "Strong Bitter" },
    { id: 85, style1: "Lambic", style2: "Weissbier", style3: "Witbier" },
    { id: 86, style1: "Dunkles Bock", style2: "Märzen", style3: "Munich Dunkel" },
    { id: 87, style1: "American Lager", style2: "American Wheat Beer", style3: "Cream Ale" },
    { id: 88, style1: "American Light Lager", style2: "Czech Pale Lager", style3: "German Leichtbier" },
    { id: 89, style1: "Festbier", style2: "Helles Bock", style3: "Munich Helles" },
    { id: 90, style1: "Czech Amber Lager", style2: "Dunkles Bock", style3: "Märzen" },
    { id: 91, style1: "American Pale Ale", style2: "Best Bitter", style3: "British Golden Ale" },
    { id: 92, style1: "Australian Sparkling Ale", style2: "Best Bitter", style3: "British Golden Ale" },
    { id: 93, style1: "Foreign Extra Stout", style2: "Irish Extra Stout", style3: "Irish Stout" },
    { id: 94, style1: "Foreign Extra Stout", style2: "Sweet Stout", style3: "Tropical Stout" },
    { id: 95, style1: "British Strong Ale", style2: "English Barleywine", style3: "Old Ale" },
    { id: 96, style1: "American IPA", style2: "Belgian Golden Strong Ale", style3: "Belgian IPA" },
    { id: 105, style1: "American Barleywine", style2: "American Strong Ale", style3: "Double IPA" },
    { id: 106, style1: "Belgian Tripel", style2: "German Pils", style3: "Trappist Single" },
    { id: 107, style1: "Czech Amber Lager", style2: "International Amber Lager", style3: "Vienna" },
    { id: 108, style1: "Czech Pale Lager", style2: "Czech Premium Pale Lager", style3: "German Pils" },
    { id: 109, style1: "American Barleywine", style2: "American Wheat Beer", style3: "Wheatwine" },
    { id: 110, style1: "American Porter", style2: "American Stout", style3: "Imperial Stout" },
  ];
  