export const beerCharacteristicsEN = [
    {value: 'cloudiness'},
    {value: 'buttery'},
    {value: 'low head retention'},
    {value: 'astringency'},
    {value: 'phenolic'},
    {value: 'light body'},
    {value: 'fruitiness'},
    {value: 'sourness'},
    {value: 'cooked corn'},
    {value: 'bitterness'},
    {value: 'cardboard'},
    {value: 'sherry-like'},
    {value: 'acetaldehyde'},
    {value: 'alcoholic'},   
]
