export const trueOrFalseMockEN: any = {
    questions: [
        { id: 1, value: true, description: 'A competition organizer may serve as the judge director and may also serve as a judge, provided this person has no knowledge of the association between entries and entrants.' },
        { id: 2, value: true, description: 'A competition’s judge director may serve as a judge, provided this person has no knowledge of the association between entries and entrants.' },
        { id: 3, value: true, description: 'A competition organizer may serve as the judge director, provided this person has no knowledge of the association between entries and entrants.' },
        { id: 4, value: false, description: 'A competition’s judge director may not serve as a judge, even if this person has no knowledge of the association between entries and entrants.' },
        { id: 5, value: false, description: 'A competition organizer may not serve as a judge, even if this person has no knowledge of the association between entries and entrants.' },
        { id: 6, value: true, description: 'A competition’s judge director may serve as the competition organizer and may also serve as a judge, provided this person has no knowledge of the association between entries and entrants.' },
        { id: 7, value: true, description: 'An individual with knowledge of the association between entries and entrants may not serve as a judge.' },
        { id: 8, value: false, description: 'A member of the competition staff with access to information that associates entries with entrants may serve as a judge, provided this person does not divulge information about entries and entrants to other judges.' },
        { id: 9, value: true, description: 'The “head” judge at a table should try to tutor apprentice or lower-rank judges if time permits.' },
        { id: 10, value: false, description: 'The steward at the table has sole responsibility for completing the Cover Sheets for beers in each flight.' },
        { id: 11, value: true, description: 'The “head” judge at the table has sole responsibility for completing the Cover Sheets for beers in each flight.' },
        { id: 12, value: true, description: 'The “head” judge at a table should fill out Cover Sheets for beers in his or her flight as directed by the competition management.' },
        { id: 13, value: false, description: 'The “head” judge at a table has no responsibility for filling out Cover Sheets for beers in his or her flight unless directed to do so by the competition management.' },
        { id: 14, value: true, description: 'The “head” judge at the table has sole responsibility for completing the Cover Sheets for beers in each flight but with the agreement of the steward may delegate the completion of the Cover Sheets to the steward.' },
        { id: 15, value: true, description: 'The “head” judge, with the agreement of the steward, may delegate filling in of the Cover Sheets for beers in his or her flight to the steward.' },
        { id: 16, value: false, description: 'There is no need for the “head” judge to complete the Flight Summary Sheet - the competition organizer can obtain all that information from the cover sheets.' },
        { id: 17, value: true, description: 'If possible, there should be at least one BJCP-ranked judge in every flight.' },
        { id: 18, value: true, description: 'When Non-BJCP judges evaluate entries in a competition, each Non-BJCP judge should be paired with a BJCP judge.' },
        { id: 19, value: true, description: 'Non-BJCP judges may only evaluate entries if authorized by the judge director, and Non-BJCP judges should be paired with BJCP judges when possible.' },
        { id: 20, value: true, description: 'To reduce stray odors and flavors present, beverages and foods other than water, bread or crackers should not be brought to the judging table.' },
        { id: 21, value: false, description: 'It is acceptable to bring food items other than bread, crackers, and water to the judging table.' },
        { id: 22, value: false, description: 'You must filter out strong scents from fellow judges or the environment from your mind rather than discussing the problem with the competition organizer.' },
        { id: 23, value: true, description: 'Strong scents from the environment or other judges or stewards should be brought to the attention of the competition organizer.' },
        { id: 24, value: false, description: 'Because entries cannot have any identifying marks, it is OK for a judge to judge beers in a category he or she has entered.' },
        { id: 25, value: true, description: 'If a judge is assigned to judge a category that he/she has entered, that judge should ask the competition organizer to reassign him/her to another category.' },
        { id: 26, value: false, description: 'If a judge is assigned to a category that he or she has entered, the judge should go ahead and evaluate the entries in that category without notifying the judge director or competition organizer.' },
        { id: 27, value: false, description: 'Judges should not review the style being judged from the BJCP Style Guidelines while at the judging table prior to judging that style.' },
        { id: 28, value: true, description: "Judges may invite stewards to taste the beers in a flight, if there's enough sample to share." },
        { id: 29, value: true, description: 'It is acceptable to change the order in which you judge the beers on your flight sheet from how it was printed.' },
        { id: 30, value: false, description: 'Beers must be evaluated in the sequence specified on the flight sheet.' },
        { id: 31, value: false, description: 'If you have eaten spicy or greasy food within a few hours prior to judging, you should use mouthwash or antiseptic rinse before judging.' },
        { id: 32, value: true, description: 'You should avoid eating spicy or greasy food within a few hours prior to judging.' },
        { id: 33, value: true, description: "Spicy or greasy foods should be avoided prior to a judging event because they can reduce a judge's sensitivity to the aromas and flavors of beer." },
        { id: 34, value: true, description: "Perfumed shampoos and colognes should be avoided prior to a judging event because they can reduce a judge's sensitivity to the aromas of beer." },
        { id: 35, value: false, description: 'It is a good idea to take a decongestant prior to a judging event to increase your sensitivity to the aromas of beer.' },
        { id: 36, value: false, description: 'Calibration beers are selected to be the standard against which entries should be judged.' },
        { id: 37, value: true, description: 'It is the responsibility of the “head” judge, in consultation with the other judges in a flight, to assign a consensus score to each entry.' },
        { id: 38, value: false, description: 'It is not necessary for scores produced by the judges on a panel to be within seven points (or less if directed by the competition director) of each other.' },
        { id: 39, value: true, description: 'After discussing the initial scores, judges should adjust their final scores to be within seven points (or less if directed by the competition director).' },
        { id: 40, value: true, description: 'Judges must adjust their scores to be within seven points (or less if directed by the competition director) of each other as part of developing a consensus score for the beer.' },
        { id: 41, value: true, description: 'The consensus score assigned to the beer is not necessarily an average score.' },
        { id: 42, value: true, description: 'When judging, it is important to evaluate entries quickly and also complete the score sheets thoroughly and completely.' },
        { id: 43, value: true, description: 'On average, experienced judges should be able to completely evaluate a beer, including arriving at a consensus, in 10 minutes.' },
        { id: 44, value: false, description: 'When there is a discrepancy in the scores for a given beer, the lower-ranked judges should yield to the opinion of the highest ranked BJCP judge at the table.' },
        { id: 45, value: true, description: 'It is acceptable to remove offensive smelling entries from the judging table after they have been evaluated.' },
        { id: 46, value: false, description: 'A judge must disqualify an entry if the bottle has raised lettering or the cap has identifying marks.' },
        { id: 47, value: false, description: 'A judge may disqualify an entry if it has an improper bottle or cap.' },
        { id: 48, value: true, description: 'Only the judge director or competition organizer can disqualify an entry.' },
        { id: 49, value: true, description: 'The results of the bottle inspection do not affect the scoring.' },
        { id: 50, value: true, description: 'Snide or rude comments are unacceptable on scoresheets.' },
        { id: 51, value: true, description: 'Pour each entry in a manner that gives it its optimum appearance, keeping in mind that some entries may be over- or under-carbonated.' },
        { id: 52, value: false, description: 'When you suspect an entry has been placed in the wrong flight based on the style being judged, you should request that it be judged in a different flight instead.' },
        { id: 53, value: true, description: 'When you suspect an entry has been placed in the wrong flight based on the style being judged, you should consult with the judge director or competition organizer.' },
        { id: 54, value: true, description: 'Sniff the entry immediately after pouring to ensure proper evaluation of volatile aromatics.' },
        { id: 55, value: false, description: 'There is no need to sniff the aroma immediately after pouring the entry into the glass.' },
        { id: 56, value: true, description: 'Judges should complete the evaluation of each entry before moving on to the next.' },
        { id: 57, value: false, description: 'It is not necessary to offer any feedback for improvement if you score a beer above 40.' },
        { id: 58, value: true, description: 'It is common practice to refrain from sharing your thoughts while judging a beer until the other judges have completed their scoresheet.' },
        { id: 59, value: false, description: 'If you are very familiar with a beer style, it is preferable to disregard the BJCP Style Guidelines and rely on your personal expertise instead.' },
        { id: 60, value: false, description: "If rushed, it's acceptable to write only comments and an overall score on a scoresheet, leaving the scores for the subsections blank." },
        { id: 61, value: false, description: "If rushed, it's acceptable to write only 1-2 comments on a scoresheet as long as the numeric score is filled out." },
        { id: 62, value: false, description: 'If a beer is a “gusher” or has an unpleasant aroma upon opening, a judge may assign a courtesy score of 13 without tasting and commenting on the characteristics of the beer.' },
        { id: 63, value: true, description: 'All beers should be tasted and scored, even if they are “gushers” or have an unpleasant aroma upon opening.' },
        { id: 64, value: false, description: 'It is appropriate to penalize the entrant if the beer is not served at the proper temperature.' },
        { id: 65, value: true, description: 'If the beers are not served at the proper temperature, judges should work with the competition staff to resolve the problem.' },
        { id: 66, value: false, description: 'In each section of a scoresheet, you should only comment upon the most prominent features of each entry, not subtle characteristics.' },
        { id: 67, value: false, description: "Judges' comments must not include phrases like 'if you used ..'" },
        { id: 68, value: false, description: "Judges' comments must not include phrases like 'did you ..'" },
        { id: 69, value: true, description: "Judges' comments must include a complete evaluation of the sensory aspects of the entry and how those aspects relate to the style guidelines." },
        { id: 70, value: true, description: "Judges' comments should be constructive and reflect knowledge of the brewing, fermentation, bottling, and handling process." },
        { id: 71, value: true, description: "Judges' comments need to provide information on how to improve the entry as warranted." },
        { id: 72, value: true, description: "Scores should not be assigned to the aroma section immediately because the entry's aroma profile may change over time." },
        { id: 73, value: false, description: 'Each section must be scored with a number prior to writing any comments, to best capture your first impressions.' },
        { id: 74, value: false, description: 'To assure objectivity, you should never write your full name or put contact information on the scoresheet.' },
        { id: 75, value: true, description: 'You should write your full name and judging rank on each scoresheet.' },
        { id: 76, value: true, description: 'You should always fill out the “Style Scales” on the scoresheet, as a good check against your scores.' },
        { id: 77, value: false, description: 'You should use the “Overall Impression” section of the scoresheet to refer to how the entry compares to other entries in the flight.' },
        { id: 78, value: true, description: 'You should use the “Overall Impression” section of the scoresheet to comment on how much you enjoyed the entry or provide suggestions for how to improve the beer.' },
        { id: 79, value: true, description: 'A score in the "Outstanding" range is reserved for entries that not only lack flaws but also have the hard-to-define "extraordinary" character that great beers have.' },
        { id: 80, value: false, description: 'The courteous lower limit for scores assigned to "Problematic" beers is 6 points, with one point for each section of the scoresheet.' },
        { id: 81, value: true, description: 'The courteous lower limit for scores assigned to “Problematic” beers is 13 points.' },
        { id: 82, value: false, description: 'If judges require more pours than one bottle to judge an entry, the “head” judge should ask the steward to request a second bottle from the cellar master.' },
        { id: 83, value: false, description: 'It is preferable to use ink on scoresheets so that your scores and comments cannot be altered by contest personnel.' },
        { id: 84, value: true, description: 'It is preferable to use mechanical pencils, rather than wooden pencils, on scoresheets so that wood odors do not interfere with beer aromas.' },
        { id: 85, value: true, description: 'It is acceptable to request a second bottle to give the entry a fair chance at an accurate judging if a beer is a “gusher” or tastes infected.' },
        { id: 86, value: true, description: 'Entrants may contact the judge, the competition director, or their BJCP Regional Representative if they are dissatisfied with any aspect of their scoresheets.' },
        { id: 87, value: true, description: 'When your flight has finished, you should avoid having conversations that might distract other judges who have not yet finished their flights.' },
        { id: 88, value: false, description: 'When your flight has finished, it is acceptable to visit other flights still in progress to see how beers you have entered are faring.' },
        { id: 89, value: true, description: 'Because it may have been entered by a person in the room, it is polite to refrain from publicly deriding a “problem” beer that you have scored during a competition.' },
        { id: 90, value: true, description: 'Judges from outside the table should not be consulted on a beer unless the judges at the table cannot reach a consensus score, and then only if they all agree to the consultation.' },
        { id: 91, value: false, description: 'BJCP Apprentice judges have not yet taken the BJCP Beer Judging Exam.' },
        { id: 92, value: true, description: 'Novice is not an official BJCP judge rank.' },
        { id: 93, value: true, description: 'One can obtain the BJCP Recognized rank without acquiring judging experience points.' },
        { id: 94, value: true, description: 'One can obtain the BJCP Recognized rank without acquiring non-judging experience points.' },
        { id: 95, value: true, description: 'To become a BJCP Certified judge, it is sufficient to pass the Entrance Exam, score at least 70% on the Beer Judging Exam and earn 5 judging points.' },
        { id: 96, value: false, description: 'To become a BJCP Certified judge, it is sufficient to pass the Entrance Exam, score at least 70% on the Beer Judging Exam and earn 5 experience points.' },
        { id: 97, value: false, description: 'The maximum score on the Beer Judging Exam for the BJCP Certified rank is 79%.' },
        { id: 98, value: false, description: 'To become a BJCP National judge, it is sufficient to score 80% on the Beer Judging Exam and accumulate 20 experience points.' },
        { id: 99, value: false, description: 'To become a BJCP National judge, it is sufficient to score 80% on the Beer Judging Exam and accumulate 20 experience points, with at least half of them from judging.' },
        { id: 100, value: false, description: 'One can obtain the BJCP National rank without acquiring judging experience points.' },
        { id: 101, value: true, description: 'One can obtain the BJCP National rank without acquiring non-judging experience points.' },
        { id: 102, value: false, description: 'BJCP Master judges must have a minimum score of 90% on the combined written and tasting exams and at least 40 judging points.' },
        { id: 103, value: false, description: 'BJCP Master judges must score at least 90% on the combined written and tasting exams and earn at least 50 experience points, with at least half of them from judging.' },
        { id: 104, value: false, description: 'The maximum score on the combined written and tasting exams for the BJCP National rank is 89%.' },
        { id: 105, value: false, description: 'BJCP Master judges must score at least 90% on the combined written and tasting exams and fulfill a Grand Master Service Requirement.' },
        { id: 106, value: false, description: 'BJCP Grand Master judges must score at least 95% on the combined written and tasting exams.' },
        { id: 107, value: true, description: 'BJCP Grand Master judges must score at least 90% on the combined written and tasting exams.' },
        { id: 108, value: true, description: 'Each additional BJCP Grand Master level requires an additional 100 experience points.' },
        { id: 109, value: true, description: 'BJCP Honorary Grand Master judges do not have to take the BJCP exam.' },
        { id: 110, value: false, description: 'The BJCP Honorary Grand Master rank is bestowed upon professional brewers when they judge at homebrew competitions.' },
        { id: 111, value: true, description: 'Honorary Master is a temporary rank bestowed on operatives of the BJCP.' },
        { id: 112, value: true, description: 'The BJCP Grand Master rank requires the same minimum score on the combined written and tasting exams as the Master rank.' },
        { id: 113, value: false, description: 'The BJCP Grand Master rank requires the same minimum experience points as the Master rank.' },
        { id: 114, value: false, description: 'The only difference in requirements between the BJCP Master and Grand Master ranks is that the Grand Master rank requires a GMSR.' },
        { id: 115, value: true, description: 'Each BJCP Grand Master level has additional requirements for exam grading.' },
        { id: 116, value: true, description: 'A BJCP Grand Master Service Requirement can be fulfilled by grading exams.' },
        { id: 117, value: false, description: 'A BJCP Grand Master Service Requirement can be fulfilled by organizing competitions.' },
        { id: 118, value: false, description: 'A BJCP Grand Master Service Requirement can be fulfilled just by serving on the BJCP Board.' },
        { id: 119, value: true, description: 'At least one-half of the experience points required for any BJCP judge rank must be from judging.' },
        { id: 120, value: false, description: 'Judging at homebrew competitions is the only way to earn BJCP judging points.' },
        { id: 121, value: true, description: 'BJCP judges can earn non-judging experience points for participating in BJCP Continuing Education Program activities.' },
        { id: 122, value: true, description: 'Judging experience points can only be earned by judging in a competition or proctoring a BJCP exam.' },
        { id: 123, value: false, description: 'Stewards at homebrew competitions earn BJCP judging points if they taste the beers with the judges.' },
        { id: 124, value: true, description: 'Stewards at homebrew competitions earn BJCP experience points.' },
    ]
}

export const trueOrFalseMockPT: any = {
    questions: [
        { id: 1, value: true, description: "Um organizador de competição pode atuar como um diretor de julgamento e também atuar como um juiz, desde que esta pessoa não tenha conhecimento da relação entre as amostras e os competidores." },
        { id: 2, value: true, description: "Um diretor de julgamento pode atuar como um juiz, desde que essa pessoa não tenha conhecimento da relação entre as amostras e os competidores." },
        { id: 3, value: true, description: "Um organizador de competição pode atuar como um diretor de julgamento, desde que esta pessoa não tenha conhecimento da relação entre as amostras e os participantes do concurso." },
        { id: 4, value: false, description: "Um diretor de julgamento não pode atuar como um juiz, mesmo que essa pessoa não tenha conhecimento da relação entre as amostras e os competidores." },
        { id: 5, value: false, description: "Um organizador de competição não pode atuar como um juiz, mesmo que essa pessoa não tenha conhecimento da relação entre as amostras e os competidores." },
        { id: 6, value: true, description: "Um diretor de julgamento pode atuar como um organizador de competição e também atuar como um juiz, desde que essa pessoa não tenha conhecimento da relação entre as amostras e os competidores." },
        { id: 7, value: true, description: "Um indivíduo com conhecimento da relação entre as amostras e os participantes do concurso não pode atuar como um juiz." },
        { id: 8, value: true, description: "Um organizador de competição pode atuar como um juiz, desde que esta pessoa não divulgue informações sobre as amostras e competidores para os outros juízes." },
        { id: 9, value: true, description: "O juiz principal da mesa deve tentar ser um supervisor do Apprentice ou juízes de níveis mais baixos se o tempo permitir." },
        { id: 10, value: false, description: "O ajudante da mesa tem a responsabilidade exclusiva de completar as Folhas de Rosto para as cervejas de cada rodada." },
        { id: 11, value: true, description: "O juiz principal da mesa tem a responsabilidade exclusiva de completar as Folhas de Rosto para as cervejas em cada rodada." },
        { id: 12, value: true, description: "O juiz principal da mesa deve preencher as Folhas de Rosto para as cervejas em sua rodada conforme orientado pela administração da competição." },
        { id: 13, value: false, description: "O juiz principal da mesa não tem a responsabilidade de preencher as Folhas de Rosto para as cervejas em sua rodada conforme orientado pela administração da competição." },
        { id: 14, value: true, description: "O juiz principal da mesa tem a responsabilidade exclusiva de completar as Folhas de Rosto para as cervejas em cada rodada, mas, com o consentimento do ajudante, pode delegar para este o preenchimento das Folhas de Rosto." },
        { id: 15, value: true, description: "O juiz principal, com o consentimento do ajudante, pode delegar para este o preenchimento das Folhas de Rosto para as cervejas de sua rodada." },
        { id: 16, value: false, description: "Não há a necessidade de o juiz principal completar a Folha de Resumo da Rodada, uma vez que o organizador da competição pode obter todas as informações a partir das folhas de rosto." },
        { id: 17, value: true, description: "Se possível, deve haver pelo menos um juiz com nível BJCP em cada rodada." },
        { id: 18, value: true, description: "Quando juízes não-BJCP avaliarem as amostras em uma competição, cada um deles deve estar junto com um juiz BJCP." },
        { id: 19, value: true, description: "Juízes não-BJCP apenas podem avaliar amostras se autorizados pelo diretor da competição, e devem ser colocados com juízes BJCP quando possível." },
        { id: 20, value: true, description: "Para reduzir a presença de odores e sabores externos, outras bebidas e comidas que água, pão ou bolachas não devem ser trazidas para a mesa de julgamento." },
        { id: 21, value: false, description: "É aceitável levar outros itens de alimentação além de pão, bolachas e água para a mesa de julgamento." },
        { id: 22, value: false, description: "Você deve filtrar da sua mente os odores fortes de juízes ao seu lado ou do ambiente ao invés de discutir o problema com o organizador da competição." },
        { id: 23, value: true, description: "Odores fortes do ambiente ou de outros juízes ou ajudantes devem ser levados ao conhecimento da organização da competição." },
        { id: 24, value: false, description: "Por causa das inscrições não poderem ter qualquer marca de identificação, é aceitável que um juiz julgue cervejas em uma categoria em que ele esteja inscrito." },
        { id: 25, value: true, description: "Se um juiz é nomeado para julgar uma categoria em que ele esteja inscrito, o juiz deve solicitar ao organizador da competição que ele seja trocado para outra categoria." },
        { id: 26, value: false, description: "Se um juiz é nomeado para uma categoria em que ele esteja inscrito, o juiz deve seguir e avaliar as amostras na categoria sem notificar o diretor de julgamento ou o organizador da competição." },
        { id: 27, value: false, description: "Juízes não devem revisar nas Diretrizes de Estilo BJCP o estilo que será julgado na mesa." },
        { id: 28, value: true, description: "Juízes podem convidar o ajudante a provar a cerveja em uma rodada, se houver quantidade suficiente da amostra para compartilhar." },
        { id: 29, value: true, description: "É aceitável mudar a ordem na qual você julga as cervejas na sua folha de resumo da rodada, diferente daquela que estava impressa." },
        { id: 30, value: false, description: "Cervejas devem ser avaliadas na sequência específica da folha de resumo da rodada." },
        { id: 31, value: false, description: "Se você tiver comido alimentos condimentados ou gordurosos poucas horas antes do julgamento, você deve usar enxágue ou antisséptico bucal antes do julgamento." },
        { id: 32, value: true, description: "Você deve evitar comer comida condimentada ou gordurosa algumas horas antes do julgamento." },
        { id: 33, value: true, description: "Comidas condimentadas ou apimentadas devem ser evitadas antes do evento de julgamento porque elas podem reduzir a sensibilidade do juiz para os aromas e sabores da cerveja." },
        { id: 34, value: true, description: "Xampus perfumados ou colônias devem ser evitados antes do evento de julgamento porque eles podem reduzir a sensibilidade do juiz para os aromas da cerveja." },
        { id: 35, value: false, description: "É uma boa ideia tomar descongestionante antes do evento de julgamento para aumentar sua sensibilidade aos aromas da cerveja." },
        { id: 36, value: false, description: "Cervejas de calibração são escolhidas para ser uma referência diante das amostras que serão julgadas." },
        { id: 37, value: true, description: "É de responsabilidade do juiz 'principal', em consulta aos outros juízes na rodada, atribuir uma nota em consenso para cada amostra." },
        { id: 38, value: false, description: "Não é necessário que as notas atribuídas pelos juízes em um júri estejam entre 7 pontos de diferença umas das outras." },
        { id: 39, value: true, description: "Após a discussão das notas iniciais, os juízes devem ajustar suas notas finais para que não tenham mais de sete pontos de diferença entre elas." },
        { id: 40, value: true, description: "Juízes devem ajustar suas notas para estarem entre sete pontos (ou menos, se orientado pelo diretor da competição) um do outro como parte do desenvolvimento de uma nota em consenso para a cerveja." },
        { id: 41, value: true, description: "A nota em consenso dada à cerveja não é necessariamente uma média das notas." },
        { id: 42, value: true, description: "Quando estiver julgando, é importante avaliar as amostras rapidamente e também preencher as súmulas com cuidado e de forma completa." },
        { id: 43, value: true, description: "Em média, juízes experientes devem ser capazes de avaliar completamente uma cerveja, incluindo chegar a um consenso, em 10 minutos." },
        { id: 44, value: false, description: "Quando há uma discrepância nas notas de uma determinada cerveja, os juízes de níveis mais baixos devem ceder à opinião dos juízes de níveis mais altos BJCP na mesa de julgamento." },
        { id: 45, value: true, description: "É aceitável remover as amostras com cheiro desagradável da mesa de julgamento após elas terem sido avaliadas." },
        { id: 46, value: false, description: "Um juiz deve desclassificar uma amostra se a garrafa tiver inscrição em relevo ou a tampa tiver marcas que a identifiquem." },
        { id: 47, value: false, description: "Um juiz pode desclassificar uma amostra se ela tiver uma garrafa ou tampa inadequada." },
        { id: 48, value: true, description: "Apenas o diretor de julgamento ou o organizador da competição podem desclassificar uma amostra." },
        { id: 49, value: true, description: "O resultado da inspeção da garrafa não afeta a nota." },
        { id: 50, value: true, description: "Comentários maliciosos ou grosseiros são inaceitáveis nas súmulas." },
        { id: 51, value: true, description: "Sirva cada amostra de maneira que consiga sua melhor aparência, tendo em mente que algumas amostras podem estar carbonatadas demais ou de menos." },
        { id: 52, value: false, description: "Quando você suspeitar que uma amostra foi colocada na rodada errada, baseado no estilo sendo julgado, você deve solicitar que ela seja julgada em uma rodada diferente." },
        { id: 53, value: true, description: "Quando você suspeitar que uma amostra foi colocada na rodada errada, baseado no estilo sendo julgado, você deve consultar o diretor de julgamento ou o organizador da competição." },
        { id: 54, value: true, description: "Cheire a amostra imediatamente após ser servida para garantir uma adequada avaliação dos voláteis aromáticos." },
        { id: 55, value: false, description: "Não há necessidade de cheirar o aroma imediatamente após a amostra ser servida no copo." },
        { id: 56, value: true, description: "Juízes devem completar a avaliação de cada amostra antes de seguir para a próxima." },
        { id: 57, value: false, description: "Não é necessário oferecer qualquer comentário para melhoria se a você der uma nota maior que 40 para a cerveja." },
        { id: 58, value: true, description: "É comum evitar a prática de compartilhar seus pensamentos enquanto estiver julgando uma cerveja até que os outros juízes tenham completado suas súmulas." },
        { id: 59, value: false, description: "Se você tiver bastante familiaridade com um estilo de cerveja, é preferível desconsiderar as Diretrizes de Estilo BJCP e contar com a sua própria opinião." },
        { id: 60, value: false, description: "Se estiver apressado, é aceitável escrever apenas comentários e uma nota geral na súmula, deixando as notas das subseções em branco." },
        { id: 61, value: false, description: "Se estiver apressado, é aceitável escrever apenas um ou dois comentários na súmula desde que a nota numérica seja preenchida." },
        { id: 62, value: false, description: "Se a cerveja é um 'gusher' (esguicho) ou tem um aroma desagradável quando aberta, o juiz pode pontuar uma nota de cortesia de 13 sem provar e comentar sobre as características da cerveja." },
        { id: 63, value: true, description: "Todas as cervejas devem ser provadas e pontuadas, mesmo se elas forem 'gushers' (esguichos) ou tiverem um aroma desagradável quando abertas." },
        { id: 64, value: false, description: "É adequado penalizar a amostra se a cerveja não for servida em uma temperatura adequada." },
        { id: 65, value: true, description: "Se as cervejas não estiverem sendo servidas na temperatura adequada, os juízes devem interagir com a equipe de apoio da competição para resolver o problema." },
        { id: 66, value: false, description: "Em cada seção da súmula, você deve apenas comentar sobre os aspectos mais importantes de cada amostra, e não características sutis." },
        { id: 67, value: false, description: "Comentários de juízes não devem incluir frases como 'se você usou...'." },
        { id: 68, value: false, description: "Comentários de juízes não devem incluir frases como 'se você fez...'." },
        { id: 69, value: true, description: "Os comentários dos juízes devem incluir uma completa avaliação dos aspectos sensoriais da amostra e como estes aspectos se correlacionam com as Diretrizes de Estilo." },
        { id: 70, value: true, description: "Comentários de juízes devem ser construtivos e refletir o conhecimento dos processos de produção de cerveja, fermentação, engarrafamento e manuseio." },
        { id: 71, value: true, description: "Comentários de juízes precisam fornecer informações de como melhorar a amostra, conforme garantido ao participante." },
        { id: 72, value: false, description: "Notas não devem ser escritas na seção de aroma imediatamente, porque o perfil do aroma das amostras pode mudar com o decorrer do tempo." },
        { id: 73, value: false, description: "Cada seção da súmula de cerveja deve ser preenchida com um número antes de escrever qualquer comentário, para melhor capturar suas primeiras impressões." },
        { id: 74, value: false, description: "Para garantir objetividade, você nunca deve escrever seu nome completo ou colocar informações de contato em suas súmulas." },
        { id: 75, value: true, description: "Você deve escrever seu nome completo e nível de juiz em cada súmula." },
        { id: 76, value: true, description: "Você deve sempre preencher as 'Escalas de Estilo' ao final da súmula, servindo como uma boa revisão para suas notas." },
        { id: 77, value: false, description: "Você deve utilizar a seção 'Impressão Geral' da súmula para referir como a amostra se compara com as outras amostras na rodada." },
        { id: 78, value: true, description: "Você deve utilizar a seção 'Impressão Geral' da súmula para comentar o quanto você gostou da amostra ou fornecer sugestões de como melhorar a cerveja." },
        { id: 79, value: true, description: "Uma nota na categoria de 'Destacado' deve ser reservada para as amostras que não apenas tenham ausência de falhas mas também que seja difícil definir a característica 'extraordinária' que só as grandes cervejas têm." },
        { id: 80, value: false, description: "O limite inferior de cortesia para as notas dadas a cervejas 'Problemáticas' é 6 pontos com um ponto para cada seção da súmula." },
        { id: 81, value: true, description: "O limite inferior de cortesia para as notas dadas a cervejas 'Problemáticas' é 13 pontos." },
        { id: 82, value: false, description: "Se os juízes precisarem mais doses do que uma garrafa para julgar uma amostra, o juiz 'principal' deve solicitar ao ajudante que peça uma segunda garrafa ao responsável pela adega." },
        { id: 83, value: false, description: "É preferível utilizar caneta nas súmulas a fim de que suas notas e comentários não possam ser alterados pela equipe de apoio da competição." },
        { id: 84, value: true, description: "É preferível utilizar lapiseiras ao invés de lápis de madeira em suas súmulas, para que o odor da madeira não interfira com os aromas da cerveja." },
        { id: 85, value: true, description: "É aceitável pedir uma segunda garrafa para dar a amostra uma oportunidade justa de um julgamento correto se a cerveja for uma 'gusher' (esguicho) ou tiver gosto de infectada." },
        { id: 86, value: true, description: "Participantes de concursos podem contatar o juiz, o diretor de competição ou o seu representante regional BJCP se estiverem insatisfeitos com qualquer aspecto de sua súmula." },
        { id: 87, value: true, description: "Quando sua rodada terminar, você deve evitar conversas que possam distrair outros juízes que ainda não terminaram sua rodada." },
        { id: 88, value: false, description: "Quando sua rodada terminar, é aceitável visitar as outras rodadas ainda em andamento para ver como as cervejas que você enviou estão indo." },
        { id: 89, value: true, description: "Por causa das amostras poderem ter sido inscritas por uma pessoa presente na sala, é elegante evitar comentários depreciativos de uma cerveja 'problema' que você estiver julgando durante uma competição." },
        { id: 90, value: true, description: "Juízes de fora da mesa não devem ser consultados sobre a cerveja, a menos que os juízes da mesa não encontram uma nota em consenso, e então somente se todos eles concordarem com a consulta." },
        { id: 91, value: false, description: "Juízes Apprentice BJCP ainda não fizeram o Exame de Julgamento de Cerveja do BJCP." },
        { id: 92, value: true, description: "'Novice' não é um nível oficial BJCP." },
        { id: 93, value: true, description: "Alguém pode obter o nível BJCP Recognized sem ter adquirido pontos de experiência em julgamento." },
        { id: 94, value: true, description: "Alguém pode obter o nível BJCP Recognized sem ter adquirido pontos de experiência fora de julgamento." },
        { id: 95, value: true, description: "Para se tornar um juiz BJCP Certified, é suficiente passar no Exame Introdutório, pontuar pelo menos 70% no Exame de Julgamento de Cerveja e conseguir 5 pontos em julgamento." },
        { id: 96, value: false, description: "Para se tornar um juiz BJCP Certified, é suficiente passar no Exame Introdutório, pontuar pelo menos 70% no Exame de Julgamento de Cerveja e conseguir 5 pontos de experiência." },
        { id: 97, value: false, description: "A nota máxima no Exame de Julgamento de Cerveja para o nível Certified é 79%." },
        { id: 98, value: false, description: "Para se tornar um juiz BJCP National, é suficiente pontuar 80% no Exame de Julgamento de Cerveja e acumular 20 pontos de experiência." },
        { id: 99, value: false, description: "Para se tornar um juiz BJCP National, é suficiente pontuar 80% no Exame de Julgamento de Cerveja e acumular 20 pontos de experiência, sendo pelo menos metade deles de julgamento." },
        { id: 100, value: false, description: "Alguém pode obter um nível BJCP National sem ter adquirido pontos de experiência em julgamento." },
        { id: 101, value: true, description: "Alguém pode obter um nível BJCP National sem ter adquirido pontos de experiência fora de julgamento." },
        { id: 102, value: false, description: "Juízes Master BJCP devem ter uma nota mínima de 90% nos exames escrito e de degustação combinados e pelo menos 40 pontos em julgamento." },
        { id: 103, value: false, description: "Juízes BJCP Master devem pontuar pelo menos 90% nos exames escrito e de degustação combinados e obter pelo menos 50 pontos de experiência, com pelo menos metade deles serem provenientes de julgamentos." },
        { id: 104, value: false, description: "A nota máxima nos exames escrito e de degustação combinados, para o nível BJCP National é 89%." },
        { id: 105, value: false, description: "Juízes BJCP Master devem pontuar pelo menos 90% nos exames escrito e de degustação combinados e cumprir Requisitos de Serviço para Grand Master." },
        { id: 106, value: false, description: "Juízes BJCP Grand Master devem pontuar pelo menos 95% nos exames escritos e de degustação combinados." },
        { id: 107, value: true, description: "Juízes BJCP Grand Master devem pontuar pelo menos 90% nos exames escritos e de degustação combinados." },
        { id: 108, value: true, description: "Cada nível adicional Grand Master BJCP exige um adicional de 100 pontos de experiência." },
        { id: 109, value: true, description: "Juízes Honorary Grand Master não têm que fazer o exame BJCP." },
        { id: 110, value: false, description: "O nível BJCP Honorary Grand Master é oferecido aos cervejeiros profissionais quando estão julgando em competições de cerveja caseira." },
        { id: 111, value: true, description: "Honorary Master é um nível temporário concedido a pessoas com função operativa dentro do BJCP." },
        { id: 112, value: true, description: "O nível BJCP Grand Master exige a mesma nota mínima que o nível Master nos exames escrito e de degustação combinados." },
        { id: 113, value: false, description: "O nível BJCP Grand Master exige o mesmo mínimo de pontos de experiência que o nível Master." },
        { id: 114, value: false, description: "A única diferença em exigências entre os níveis BJCP Master e Grand Master é que o nível Grand Master exige um Requisito de Serviço para Grand Master." },
        { id: 115, value: true, description: "Cada nível de Grand Master BJCP tem requisitos adicionais de correção de exames." },
        { id: 116, value: true, description: "Um Requisito de Serviço para Grand Master BJCP pode ser alcançado corrigindo exames." },
        { id: 117, value: false, description: "Um Requisito de Serviço para Grand Master BJCP pode ser alcançado organizando competições." },
        { id: 118, value: false, description: "Um Requisito de Serviço para Grand Master BJCP pode ser alcançado fazendo parte da diretoria do BJCP." },
        { id: 119, value: true, description: "Pelo menos metade dos pontos de experiência exigidos para qualquer classificação de juiz BJCP devem ser de julgamento." },
        { id: 120, value: false, description: "Julgamento nas competições de cerveja caseira é a única forma de conseguir pontos em julgamento." },
        { id: 121, value: true, description: "Juízes BJCP podem ganhar pontos de experiência fora de julgamento participando de atividades do Programa de Educação Continuada do BJCP." },
        { id: 122, value: true, description: "Pontos de experiência em julgamento podem apenas ser conseguidos por julgamento em uma competição ou supervisionando um exame BJCP." },
        { id: 123, value: false, description: "Ajudantes nas competições de cerveja caseira ganham pontos em julgamento BCJP se eles degustarem as cervejas junto com os juízes." },
        { id: 124, value: true, description: "Ajudantes nas competições de cerveja caseira ganham pontos de experiência BCJP." },
                
    ]
    
}